version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [sh, -c, "yarn run install-start && npm run forever"]
    ports:
      - "80:8888"
      - "443:8888"
    volumes:
      - ./:/app
