version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn --silent && yarn run start
    ports:
      - "80:8888"
      - "81:8888"
    volumes:
      - ./:/app
