version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [sh, -c, "yarn --silent & npm run forever && yarn run start"]
    ports:
      - "80:8888"
      - "443:8888"
    volumes:
      - ./:/app
